# Generated by Django 2.2.14 on 2020-07-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil_price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oilprice',
            name='date',
            field=models.DateField(auto_created=None),
        ),
    ]
